battle/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^waiting$', views.waiting, name='waiting'),
]

chess/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^battle/', include('battle.urls',namespace='battle')),
    url(r'^admin/', admin.site.urls),
]

presences/models.py
from django.db import models
from django.utils.timezone import now
from django.conf import settings
from channels.layers import get_channel_layer
from django.contrib.auth import get_user_model
from datetime import timedelta
from presences.signals import presence_changed


class PresenceManager(models.Manager):
    def touch(self,channel_name):
        """
        presenceがRoomにいる時間を更新
        """
        self.filter(channel_name=channel_name).update(last_seen=now())

    def leave_all(self,channel_name):
        """
        すべての部屋からこのPresenceインスタンスを削除
        """
        # select_relatedを使うと外部キーのテーブルを取得しキャッシュできる
        for presence in self.select_related('room').filter(channel_name=channel_name):
            room = presence.room
            room.remove_presence(presence=presence)
    
class Presence(models.Model):
    room = models.ForeignKey('Room',on_delete=models.CASCADE)   # 外部キーroom
    channel_name = models.CharField(max_length=255)             # channel名
    # ユーザーはカスタマイズすることを考えてsettingsから取ってくる
    #user = models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.CASCADE)
    # auto_nowやauto_now_addを使うと時間の自由な更新ができなくなるためdatetime.nowを使用
    last_seen = models.DateTimeField(default=now)
    objects = PresenceManager()
    def __sr__(self):
        return self.channel_name

    class Meta:
        # 部屋ごとに同じchannel_nameは一人まで
        unique_together = [('room','channel_name')]
        ordering=['last_seen']

class RoomManager(models.Manager):
    def add(self,room_channel_name,user_channel_name,user=None):
        """
        user_channel_nameをroom_channel_nameと名前のついたRoomに追加.
        もし必要ならRoom,Presenceインスタンスの作成,Groopの追加も行う.
        """
        # Roomの取得,なければ作成
        room,created = Room.objects.get_or_create(channel_name=room_channel_name)
        room.add_presence(user_channel_name)
        return room
    def remove(self,room_channel_name,user_channel_name):
        """
        user_channel_nameをroom_channel_nameで指定されたRoomから削除
        それに対するPresenceインスタンスも削除しGroupを更新
        """
        # 指定されたRoomが存在すれば取得
        try:
            room = Room.objects.get(channel_name=room_channel_name)
        except Room.DoesNotExist:
            return
        room.remove_presence(user_channel_name)
    def prune_presences(self,channel_layer=None,age=None):
        """
        age_in_secondsより前のlast_seenのPresenceインスタンスを削除する
        age_in_secondsはsettings.CHANNEL_PRESENCE_MAX_AGEでデフォルト値を定義できる
        """
        for room in Room.objects.all():
            room.prune_presences(age)
    def prune_rooms(self):
        """
        PresenceインスタンスのないRoomを削除
        """
        Room.objects.filter(presence__isnull=True).delete()

class Room(models.Model):
    channel_name = models.CharField(max_length=255,unique=True)
    objects = RoomManager()
    def __str_(self):
        return self.channel_name
    def get_all_presence(self):
        return Presence.objects.filter(room=self.id)
    def add_presence(self,channel_name):
        """
        ユーザーが認証済か確認しPresenceインスタンスを作成
        """
        # 認証状態の確認
        # authenticated = user and(
        #     callable(user.is_authenticated) and user.is_authenticated()
        # )
        presence , created = Presence.objects.get_or_create(
            room = self,
            channel_name = channel_name
        )
        if created:
            channel_layer = get_channel_layer()
            # グループにチャンネルを追加
            channel_layer.group_add(self.channel_name,channel_name)
            self.broadcast_channged(added=presence)
    def remove_presence(self,channel_name=None,presence=None):
        """
        channel_nameをroomから削除
        presenceかchannel_nameを指定
        """
        if presence is None:
            try:
                presence = Presence.objects.get(room=self,channel_name=channel_name)
            except Presence.DoesNotExist:
                return
        # グループからchannel_nameを削除
        channel_layer = get_channel_layer()
        channel_layer.group_discard(self.channel_name,channel_name)
        # presenceインスタンスを削除
        presence.delete()
        self.broadcast_channged(removed=presence)
    def prune_presences(self,age_in_seconds=None):
        if age_in_seconds is None:
            # settings.pyからCHANNELS_PRESENCE_MAX_AGEを取得(default=60))
            age_in_seconds = getattr(settings , "CHANNELS_PRESENCE_MAX_AGE",60)
        # age_in_secondsより長い時間更新されていないPresenceを削除
        num_deleted,num_per_type = Presence.objects.filter(
            room=self,
            last_seend__lt=now() - timedelta(seconds=age_in_seconds)
        ).delete()
        if num_deleted > 0:
            self.broadcast_channged(bulk_change=True)
        
    def get_users(self):
        """
        Room内の認証済ユーザーリストを返す
        """
        # User = get_user_model()
        # return User.objects.filter(presence__room=self).distinct()
        pass
    def get_anonymous_count(self):
        """
        userがNoneのpresenseをすべて取得
        [CHANGED]
        """
        # return self.presence_set.filter(user=None).count()
        return self.presence_set.all()
    def broadcast_channged(self,added=None,removed=None,bulk_change=False):
        presence_changed.send(
            sender=self.__class__,
            room=self,
            added=added,
            removed=removed,
            bulk_change=bulk_change
        )

battle/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
from django.views.decorators.csrf import csrf_exempt
import json

def index(request):
    return render(request, 'battle/index.html', {})
@csrf_exempt
def waiting(request):
    username = request.POST["user-name"]
    context = {
        "username":username
    }
    return render(request,'battle/waiting.html',context)

def room(request, room_name):
    context = {
        'room_name_json': mark_safe(json.dumps(room_name))
    }
    return render(request, 'battle/room.html', context)



            

presences/views.py
from django.shortcuts import render

# Create your views here.

battle/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <title>Example Channels</title>
</head>
<body>
  <div class="container">
    <br>
    {% block content %}{% endblock content %}
  </div>
  <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
  {% block script %}{% endblock script %}
</body>
</html>

battle/templates/battle/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chess Rooms</title>
</head>
<body>
    そうら!入室じゃ!
    <form action="{% url 'battle:waiting' %}" method="POST" >
    <input id="room-name-input" name="user-name"><br/>
    <input id="room-name-submit" type="submit" value="Enter"/>
    </form>
    <script>
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, returnを押したら送信
                document.querySelector('#room-name-submit').click();
            }};
        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '//' + roomName + '/';
        };
    </script>
</body>
</html>

battle/templates/battle/room.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>
<script>
    // room名を受け取る
    var roomName = {{ room_name_json }};
    
    // ウェブソケット作成
    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/battle/' + roomName + '/');
    // メッセージ作成
    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    // クローズ時の処理
    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    
    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>
</html>

battle/templates/battle/user_list.html
{% extends 'base.html' %}

{% block content %}{% endblock content %}

{% block script %}
  <script>
    var socket = new WebSocket('ws://' + window.location.host + '/users/');

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
    };

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
  </script>
{% endblock script %}

battle/templates/battle/waiting.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
</body>
<script>
    // room名を受け取る
    var userName = "{{ username }}";
    
    // ウェブソケット作成
    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/waiting/' + userName + '/');
    // メッセージ作成
    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        console.log(data);
    };

    // クローズ時の処理
    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    setInterval(function() {
        chatSocket.send(JSON.stringify({"type":"heartbeat","message":""}));
    }, 30000);

    //chatSocket.onopen = () => chatSocket.send(JSON.stringify({
    //    'message': userName,
    //}));
</script>
</html>